name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "32 6 * 2 2"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'old issue sanse activity message'
        stale-pr-message: 'old issue sanse activity pull request message'
        stale-issue-label: 'old issue sanse activity'
        stale-pr-label: 'old pr sanse activity'
